// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCndXArbQKpriLVk4IGaytcV-16m4AJDGw',
    appId: '1:541418061981:web:d27f75108d2318044dd474',
    messagingSenderId: '541418061981',
    projectId: 'e-commerce-3aa9a',
    authDomain: 'e-commerce-3aa9a.firebaseapp.com',
    storageBucket: 'e-commerce-3aa9a.appspot.com',
    measurementId: 'G-DMB3HXQRD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCLNUaLPX69w3Gv4TBJXbhreGKlKXjpl8',
    appId: '1:541418061981:android:2790e43cc1708abf4dd474',
    messagingSenderId: '541418061981',
    projectId: 'e-commerce-3aa9a',
    storageBucket: 'e-commerce-3aa9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA9Djo4Em77gsPXgiFqoiKUkX15yr-Wpo',
    appId: '1:541418061981:ios:77a91122561ff2c74dd474',
    messagingSenderId: '541418061981',
    projectId: 'e-commerce-3aa9a',
    storageBucket: 'e-commerce-3aa9a.appspot.com',
    iosClientId: '541418061981-8daed5m5tcnj2net0b2bejo8jec24jls.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA9Djo4Em77gsPXgiFqoiKUkX15yr-Wpo',
    appId: '1:541418061981:ios:77a91122561ff2c74dd474',
    messagingSenderId: '541418061981',
    projectId: 'e-commerce-3aa9a',
    storageBucket: 'e-commerce-3aa9a.appspot.com',
    iosClientId: '541418061981-8daed5m5tcnj2net0b2bejo8jec24jls.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
